version: '3.8'
services:
  # Redis for job queue
  redis:
    image: redis:7-alpine
    container_name: redis_queue
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  # Service 1: Transcribe & Download
  service1:
    container_name: transcribe_service
    build:
      context: ./service1
    ports:
      - "3001:3001"
    volumes:
      - ./service1:/app
      - media_data:/data
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    restart: unless-stopped
  # Service 2: Clip Creation
  service2:
    container_name: clip_service
    build:
      context: ./service2
    ports:
      - "3002:3002"
    volumes:
      - ./service2:/app
      - media_data:/data
    restart: unless-stopped
  # Service 3: Long Video Editor
  service3:
    container_name: editor_service
    build:
      context: ./service3
    ports:
      - "3003:3003"
    volumes:
      - ./service3:/app
      - media_data:/data          # ВОТ ЭТО ВАЖНО!
      - /media_upload:/media_upload:ro
      - /var/www/clips:/var/www/clips
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  # Service 4: Publish Shorts
  service4:
    container_name: publish_shorts_service
    build:
      context: ./service4
    ports:
      - "3004:3004"
    volumes:
      - ./service4:/app
      - media_data:/data
      - /var/www/clips:/var/www/clips  # ДОБАВЛЕНО
    restart: unless-stopped
  # Service 5: Publish Long Videos
  service5:
    container_name: publish_long_service
    build:
      context: ./service5
    ports:
      - "3005:3005"
    volumes:
      - ./service5:/app
      - media_data:/data
    restart: unless-stopped
volumes:
  media_data:
  redis_data:
